#include "nsISupports.idl"

[scriptable, uuid(2e4ccfe4-4119-433d-92df-4e84cef81ae8)]
interface ILoxPromise : nsISupports {
    void resolve(in ACString value);
    void reject(in ACString error);
};

[scriptable, uuid(3855b9c2-2358-4135-a35c-f95d4f4f2069)]
interface ILoxServiceHelper : nsISupports {
    void runRequest(in ACString procedure, in ACString request,
                    in ILoxPromise promise);
    void store(in ACString data);
};

[scriptable, uuid(5fbd1f22-7d65-430f-bd82-43c574c364a2)]
interface ILoxService : nsISupports {
    void initialize(in ILoxServiceHelper helper, in ACString data);
    void uninitialize();

    Array<ACString> getBridges(in ACString loxId);
    boolean validateInvitation(in ACString invitation);
    Array<ACString> getInvites();
    unsigned long getNumInvites();
    unsigned long getRemainingInviteCount(in ACString loxId);
    ACString getEventData();

    void redeemInvite(in ACString invite, in ILoxPromise promise);
    void generateInvite(in ACString loxId, in ILoxPromise promise);
};
